"""initial schema

Revision ID: 824e73e089cc
Revises: 
Create Date: 2026-02-11 18:42:36.620889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '824e73e089cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('github_user_id', sa.BigInteger(), nullable=True),
    sa.Column('github_login', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True, comment='Bcrypt hashed password for local authentication'),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True, comment='Encrypted GitHub personal access token'),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('github_login'),
    sa.UniqueConstraint('github_user_id')
    )
    op.create_table('hourly_activity',
    sa.Column('activity_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('hour_of_day', sa.SmallInteger(), nullable=False),
    sa.Column('commit_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pr_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('additions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deletions', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='ck_hourly_activity_day_of_week'),
    sa.CheckConstraint('hour_of_day >= 0 AND hour_of_day <= 23', name='ck_hourly_activity_hour_of_day'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('activity_id'),
    sa.UniqueConstraint('user_id', 'activity_date', 'hour_of_day', name='uq_hourly_activity_user_date_hour')
    )
    op.create_table('repositories',
    sa.Column('repo_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('github_repo_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_language', sa.String(length=100), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('repo_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_synced_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('repo_id'),
    sa.UniqueConstraint('github_repo_id')
    )
    op.create_table('commits',
    sa.Column('commit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('github_commit_sha', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('committed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('additions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deletions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('changed_files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.repo_id'], ),
    postgresql_partition_by='RANGE (committed_at)'
    )
    op.create_table('gemini_analyses',
    sa.Column('analysis_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('tech_tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('work_category', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('complexity_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('analyzed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('commit', 'pull_request', 'weekly_summary', 'monthly_summary')", name='ck_gemini_analyses_source_type'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.repo_id'], ),
    postgresql_partition_by='RANGE (analyzed_at)'
    )
    op.create_table('pull_requests',
    sa.Column('pr_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('github_pr_id', sa.BigInteger(), nullable=False),
    sa.Column('github_pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=50), server_default='open', nullable=False),
    sa.Column('additions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deletions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('changed_files', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pr_created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('pr_closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('merged_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.repo_id'], ),
    postgresql_partition_by='RANGE (pr_created_at)'
    )
    op.create_table('sync_jobs',
    sa.Column('job_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('items_fetched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name='ck_sync_jobs_status'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.repo_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_jobs')
    op.drop_table('pull_requests')
    op.drop_table('gemini_analyses')
    op.drop_table('commits')
    op.drop_table('repositories')
    op.drop_table('hourly_activity')
    op.drop_table('users')
    # ### end Alembic commands ###
